version: '3.1'

services:
  backend:
    build:
      context: ./api
    command: gunicorn api.wsgi:application --bind 0.0.0.0:8000
    ports:
     - "8000:8000"
  
  frontend:
    build:
      context: ./react/frontend
    volumes:
     - react_build:/react/build
    expose:
     - 3000
    ports:
     - "3000:3000"
    stdin_open: true
   

  nginx:
    image: nginx:latest
    ports:
     - 80:80
    volumes:
     - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
     - react_build:/var/www/react
    depends_on:
     - backend
     - frontend

volumes:
  react_build: